<% require "dotenv"; Dotenv.load(".env") %>

service: rails_test
image: lightflight/rails_test

servers:
  web:
    - 89.169.181.176

proxy:
  ssl: true
  host: rails-test.ru

registry:
  username: lightflight
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    POSTGRES_USER: rails_test
    POSTGRES_DB: rails_test_production
    POSTGRES_HOST: 89.169.181.176
    REDIS_URL: 'redis://rails-test-redis:6379/'

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: deploy
  keys: ["~/.ssh/id_ed25519.pub"]

accessories:
  db:
    image: postgres:16.1
    host: 89.169.181.176
    port: 5432
    env:
      clear:
        POSTGRES_USER: rails_test
        POSTGRES_DB: rails_test_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - 'data:/var/lib/postgresql/data'
  redis:
    image: 'redis:7.2'
    host: 89.169.181.176
    port: 6379
    directories:
      - 'data:/data'
